# Dev environment
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./src/docker/mongo-init:/docker-entrypoint-initdb.d  # init-mongo.js

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"