# Dev environment
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./src/docker/mongo-init:/docker-entrypoint-initdb.d # init-mongo.js

  redis:
    image: redis:7-alpine
    container_name: redis_pubsub
    ports:
      - "6379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  web:
    image: interpreto-web
    ports:
      - "8081:8080"
    depends_on:
      - mongo
      - redis
      - minio
    env_file:
      - .env
